version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - setup_remote_docker
      - checkout
      - run: go get -v ./...
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.16.0
      - run: sudo cp ./bin/golangci-lint $GOPATH/bin/
      - run: make lint
      - run: make test
