version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - setup_remote_docker
      - checkout
      - run: go get -v ./...
      - run: make lint
      - run: make test
